import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * The plugin's schema (ADR 0002): the tally_command ledger and the Order and OrderLine custom-field
 * columns, generated by Vendure's generateMigration against Postgres 16 from a schema without the
 * plugin. The two plain indexes on the register and session ids match the TypeORM metadata that
 * registerOrderIndexes puts on CustomOrderFields; test/migration.e2e.ts proves the whole migration
 * and an empty schema diff after it.
 */
export class TallyPos1790648006022 implements MigrationInterface {
  name = 'TallyPos1790648006022';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE "tally_command" ("id" character varying NOT NULL, "clientOrderId" character varying NOT NULL, "fingerprint" character varying NOT NULL, "status" character varying NOT NULL, "result" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cb557f149dd2aba503ab051d4fa" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_78583fdb4ec084e117c6cf9575" ON "tally_command" ("clientOrderId") `);
    await queryRunner.query(`ALTER TABLE "order" ADD "customFieldsTallyclientorderid" character varying(255)`);
    await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "UQ_ff88d64a4e987b9203e7d767f46" UNIQUE ("customFieldsTallyclientorderid")`);
    await queryRunner.query(`ALTER TABLE "order" ADD "customFieldsTallysaleat" TIMESTAMP(6)`);
    await queryRunner.query(`ALTER TABLE "order" ADD "customFieldsTallyregisterid" character varying(255)`);
    await queryRunner.query(`ALTER TABLE "order" ADD "customFieldsTallysessionid" character varying(255)`);
    await queryRunner.query(`ALTER TABLE "order" ADD "customFieldsTallycashierref" character varying(255)`);
    await queryRunner.query(`ALTER TABLE "order" ADD "customFieldsTallypayments" text`);
    await queryRunner.query(`ALTER TABLE "order" ADD "customFieldsTallysnapshot" text`);
    await queryRunner.query(`ALTER TABLE "order_line" ADD "customFieldsTallyunitprice" integer`);
    await queryRunner.query(`ALTER TABLE "order_line" ADD "customFieldsTallyclientlineid" character varying(255)`);
    await queryRunner.query(`ALTER TABLE "order_line" ADD "customFieldsTallypriceincludestax" boolean`);
    // Plain indexes for register and session lookups (registerOrderIndexes, ruling 2).
    await queryRunner.query(`CREATE INDEX "IDX_tally_order_register_id" ON "order" ("customFieldsTallyregisterid")`);
    await queryRunner.query(`CREATE INDEX "IDX_tally_order_session_id" ON "order" ("customFieldsTallysessionid")`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX "public"."IDX_tally_order_session_id"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_tally_order_register_id"`);
    await queryRunner.query(`ALTER TABLE "order_line" DROP COLUMN "customFieldsTallypriceincludestax"`);
    await queryRunner.query(`ALTER TABLE "order_line" DROP COLUMN "customFieldsTallyclientlineid"`);
    await queryRunner.query(`ALTER TABLE "order_line" DROP COLUMN "customFieldsTallyunitprice"`);
    await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customFieldsTallysnapshot"`);
    await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customFieldsTallypayments"`);
    await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customFieldsTallycashierref"`);
    await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customFieldsTallysessionid"`);
    await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customFieldsTallyregisterid"`);
    await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customFieldsTallysaleat"`);
    await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "UQ_ff88d64a4e987b9203e7d767f46"`);
    await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customFieldsTallyclientorderid"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_78583fdb4ec084e117c6cf9575"`);
    await queryRunner.query(`DROP TABLE "tally_command"`);
  }
}
