import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * The register commands (ADR 0003): the write-once register, session, status, movement and closure tables, and a
 * ledger clientOrderId that a register command leaves null. Generated by TypeORM's schema builder against Postgres 16;
 * test/migration.e2e.ts proves the migration and an empty schema diff after it.
 */
export class TallyPosRegister1790800000000 implements MigrationInterface {
  name = 'TallyPosRegister1790800000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE "tally_register" ("channelId" character varying NOT NULL, "id" character varying NOT NULL, "receivedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_330cffe5f4469e0c7f55994b786" PRIMARY KEY ("channelId", "id"))`);
    await queryRunner.query(`CREATE TABLE "tally_register_session" ("channelId" character varying NOT NULL, "id" character varying NOT NULL, "registerId" character varying NOT NULL, "storeKey" character varying, "businessDay" character varying, "openedAt" character varying NOT NULL, "openedBy" character varying, "expectedFloatMinor" bigint, "countedFloatMinor" bigint NOT NULL, "openingVarianceMinor" bigint, "commandId" character varying NOT NULL, "receivedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_694799ddf1a169afc649e41ec4b" PRIMARY KEY ("channelId", "id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_57884f6d20b5ab78302240976b" ON "tally_register_session" ("channelId", "registerId") `);
    await queryRunner.query(`CREATE TABLE "tally_register_session_status" ("seq" SERIAL NOT NULL, "channelId" character varying NOT NULL, "sessionId" character varying NOT NULL, "status" character varying NOT NULL, "at" character varying NOT NULL, "counted" text, "closedBy" character varying, "approvedBy" character varying, "commandId" character varying NOT NULL, "receivedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e3bf54fd35c91c8b9813c6ba23f" PRIMARY KEY ("seq"))`);
    await queryRunner.query(`CREATE INDEX "IDX_e1da3bd8299c5d80a4313dc675" ON "tally_register_session_status" ("channelId", "sessionId") `);
    await queryRunner.query(`CREATE TABLE "tally_register_movement" ("channelId" character varying NOT NULL, "id" character varying NOT NULL, "sessionId" character varying NOT NULL, "type" character varying NOT NULL, "amountMinor" bigint NOT NULL, "reason" character varying, "voids" character varying, "createdAt" character varying NOT NULL, "createdBy" character varying, "commandId" character varying NOT NULL, "receivedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_50e2490a4c8604fe712a3934543" UNIQUE ("channelId", "voids"), CONSTRAINT "PK_441df0923693354d46e6dc30d5e" PRIMARY KEY ("channelId", "id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_b67faa4ff7b28e4af0694dd306" ON "tally_register_movement" ("channelId", "sessionId") `);
    await queryRunner.query(`CREATE TABLE "tally_register_closure" ("channelId" character varying NOT NULL, "id" character varying NOT NULL, "sessionId" character varying NOT NULL, "registerId" character varying NOT NULL, "number" integer NOT NULL, "businessDay" character varying, "openedAt" character varying NOT NULL, "closedAt" character varying NOT NULL, "closedBy" character varying, "approvedBy" character varying, "tillExpected" text NOT NULL, "counted" text NOT NULL, "periodSalesTotalMinor" bigint NOT NULL, "periodRefundsTotalMinor" bigint NOT NULL, "perpetualSalesTotalMinor" bigint NOT NULL, "perpetualRefundsTotalMinor" bigint NOT NULL, "unsyncedCount" integer NOT NULL, "unsyncedTotalMinor" bigint NOT NULL, "softwareVersion" character varying NOT NULL, "orderIds" text NOT NULL, "movementIds" text NOT NULL, "expected" text NOT NULL, "variance" text NOT NULL, "commandId" character varying NOT NULL, "receivedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fdc8938aa0359ee820b04de0376" UNIQUE ("channelId", "registerId", "number"), CONSTRAINT "UQ_82e1f0bdede8def7051d66f0740" UNIQUE ("channelId", "sessionId"), CONSTRAINT "PK_8d97c69187624fabbee2bff5955" PRIMARY KEY ("channelId", "id"))`);
    await queryRunner.query(`ALTER TABLE "tally_command" ALTER COLUMN "clientOrderId" DROP NOT NULL`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // The register commands' ledger rows go with their tables.
    await queryRunner.query(`DELETE FROM "tally_command" WHERE "clientOrderId" IS NULL`);
    await queryRunner.query(`ALTER TABLE "tally_command" ALTER COLUMN "clientOrderId" SET NOT NULL`);
    await queryRunner.query(`DROP TABLE "tally_register_closure"`);
    await queryRunner.query(`DROP TABLE "tally_register_movement"`);
    await queryRunner.query(`DROP TABLE "tally_register_session_status"`);
    await queryRunner.query(`DROP TABLE "tally_register_session"`);
    await queryRunner.query(`DROP TABLE "tally_register"`);
  }
}
